apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongo-express-deployment
  labels:
    app: mongp-express

spec:
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  key: mongo-root-username
                  name: mongodb-secrets
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongo-root-password
                  name: mongodb-secrets
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: database-url
                  name: mongodb-configmap

---
apiVersion: v1
kind: Service

metadata:
  name: mongo-express-service

spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30081

---
# this is not working for some reason
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: mongo-express-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - host: mongokube.com
      http:
        paths:
          - backend:
              service:
                name: mongo-express-service
                port:
                  number: 8081
            path: /
            pathType: Prefix

