apiVersion: v1
kind: PersistentVolume

metadata:
  name: mongodb-volume
  labels:
    app: mongodb-volume

spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data"
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
